[package]
name = "collectune"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
symphonia = { version = "0.5", features = ["all"] }
duckdb = { version = "1.4.4", features = ["bundled"] }
